### ISSUE TITLE
segmenation fault

### ISSUE THREAD

**Issue by wolfshow** [nand2mario/nestang#11]
why do I get segmentation fault when loading the newly released 0.5, but no problem with 0.5rc

**Comment by Chandler-Kluser** [comment]
can you provide more details about the build configuration?

**Comment by wolfshow** [comment]
> can you provide more details about the build configuration?

![image](https://github.com/nand2mario/nestang/assets/3775235/3d0eba6b-2b7d-4110-aa0d-d2a974c88178)

**Comment by wolfshow** [comment]
> Can you provide more details like:
> 
> * Were you able to write it into SRAM?
    I haven't tried this yet because I am able to write 0.5rc.

> * What openFPGALoader build did you use?
    The latest build.

> * Did you try to flash using Gowin Programmer?
    No, I did not use Gowin Programmer.

**Comment by Chandler-Kluser** [comment]
I believe the issue can be in openFPGALoader, I have already faced ![issues](https://github.com/trabucayre/openFPGALoader/issues/250) in Tang Primer 20k by writing its flash memory and did not have any by using the Official Programmer.

Another detail could be any kind of bitstream generation by using nextpnr, for instance. But I don't know if you placed and routed with gw_sh or nextpnr.

I will try to reproduce your steps here.

**Comment by wolfshow** [comment]
> I believe the issue can be in openFPGALoader, I have already faced ![issues](https://github.com/trabucayre/openFPGALoader/issues/250) in Tang Primer 20k by writing its flash memory and did not have any by using the Official Programmer.
> 
> Another detail could be any kind of bitstream generation by using nextpnr, for instance. But I don't know if you placed and routed with gw_sh or nextpnr.
> 
> I will try to reproduce your steps here.

Thanks! For the official GOWIN programmer, do I need to use version 1.99 with commercial license? or 1.98 is fine?

**Comment by Chandler-Kluser** [comment]
the Educational Edition is fine, because there is support for Tang Nano 20k
