### ISSUE TITLE
controller using arduino micro successfully connects tang nano 20k

### ISSUE THREAD

**Issue by wolfshow** [nand2mario/nestang#15]
![image](https://github.com/nand2mario/nestang/assets/3775235/2e5b88fa-332b-49bf-9074-27166643a92c)

https://github.com/nand2mario/nestang/assets/3775235/9c4a18c6-df27-47bb-bb81-bff51acaf941

**Comment by nand2mario** [comment]
Cool. What protocol is the arduino using to talk to the Nano 20k?

**Comment by wolfshow** [comment]
> Cool. What protocol is the arduino using to talk to the Nano 20k?

use an arduino psx driver to talk to the 20k

**Comment by Chandler-Kluser** [comment]
I have posted a [project with bluetooth support](https://www.youtube.com/watch?v=wjiUXOrpm1Q) by merging [hi631](https://github.com/hi631/tang-nano-9K) NES core with the DS2 from [nestang](https://github.com/nand2mario/nestang) project.

**Comment by Epyc7** [comment]
> ![image](https://user-images.githubusercontent.com/3775235/247180754-2e5b88fa-332b-49bf-9074-27166643a92c.jpeg)
> 
>  Upload.from.GitHub.for.iOS.MOV

Would you mind posting instructions somewhere on how to implement this?

**Comment by Epyc7** [comment]
> I have posted a [project with bluetooth support](https://www.youtube.com/watch?v=wjiUXOrpm1Q) by merging [hi631](https://github.com/hi631/tang-nano-9K) NES core with the DS2 from [nestang](https://github.com/nand2mario/nestang) project.

Would love to also implement this.  Do you have instructions?

**Comment by Chandler-Kluser** [comment]
> > I have posted a [project with bluetooth support](https://www.youtube.com/watch?v=wjiUXOrpm1Q) by merging [hi631](https://github.com/hi631/tang-nano-9K) NES core with the DS2 from [nestang](https://github.com/nand2mario/nestang) project.
> 
> Would love to also implement this. Do you have instructions?

I have made a [side repository](https://github.com/Chandler-Kluser/nestang9k-ps2) with [hi631](https://github.com/hi631/tang-nano-9K) NES implementation and [nestang](https://github.com/nand2mario/nestang) DS2 interface to be handled by an esp32 with blueretro.

Instructions in README

**Comment by Epyc7** [comment]
> > > I have posted a [project with bluetooth support](https://www.youtube.com/watch?v=wjiUXOrpm1Q) by merging [hi631](https://github.com/hi631/tang-nano-9K) NES core with the DS2 from [nestang](https://github.com/nand2mario/nestang) project.
> > 
> > 
> > Would love to also implement this. Do you have instructions?
> 
> I have made a [side repository](https://github.com/Chandler-Kluser/nestang9k-ps2) with [hi631](https://github.com/hi631/tang-nano-9K) NES implementation and [nestang](https://github.com/nand2mario/nestang) DS2 interface to be handled by an esp32 with blueretro.
> 
> Instructions in README

I noticed this was for the Tang Nano 9k.  Is the instructions still the same for the Tang Nano 20k?
