### ISSUE TITLE
Distributing config file impl/project_process_config.json

### ISSUE THREAD

**Issue by somhi** [nand2mario/nestang#20]
Config file impl/project_process_config.json should be distributed for Gowin projects, IMHO.
Then reading the info from https://nand2mario.github.io/nestang-doc/dev/build_bitstream/  might not be required to build the project, although it is good to know it.

Just need to add following folders to .gitignore
gwsynthesis
pnr
temp

**Comment by nand2mario** [comment]
Thanks for catching this. I just added the file.
