### ISSUE TITLE
ERROR   EX3937 : instantiating unknown module 'DSP48A1'(/src/dsp.v:63)

### ISSUE THREAD

**Issue by somhi** [nand2mario/nestang#22]
While building project on Gowin IDE I'm getting that error.

Could be that module a Gowin primitive only present in Licensed version?
I'm using the educational version.

**Comment by Chandler-Kluser** [comment]
I have not had issues when I built from source a time ago using the Educational IDE. Have you followed the build instructions?

**Comment by somhi** [comment]
Yes I did. I could not find that module so I guess is a Gowin primitive.

**Comment by nand2mario** [comment]
As @Chandler-Kluser said, the current project should be working fine.

Actually dsp.v is not used anymore. So you can just remove the file. I'll remove the file later.
