### ISSUE TITLE
NES file loader

### ISSUE THREAD

**Issue by windship** [nand2mario/nestang#24]
Currently I have to make games.img from my NES rom files collection but this is so uncomfortable. I have about 1,000 NES files but I can't make a games.img file including my all roms(because of max letter limit for one dos command). And I have to make another games.img file if I want to delete some roms from my SD card every time. Please enhance the loader that can load *.NES rom from SD card folder after selecting from the rom list. I don't know why games.img packing needed.

**Comment by nand2mario** [comment]
I'm looking at file system support, now that USB gamepad is done in v0.6 (at least for a first version).

**Comment by nand2mario** [comment]
FAT32 support is released in v0.7. Enjoy.
