### ISSUE TITLE
Freezes/Resets on Roms Selection

### ISSUE THREAD

**Issue by s3anami** [nand2mario/nestang#30]
When I select a rom the device freezes or sometimes resets itself. Not sure how to troubleshoot behavior

**Comment by mariogazziro** [comment]
i notice that version 0.6 has a more stable menu system related to joystick selection without freezing.. i think that something in FAT sd card reader in 0.7.1 version compromise the menu system

**Comment by s3anami** [comment]
Is there a way for me to provide logs? I couldnt get usb pad working either, tried the wireless xbox receiver mentioned in wiki. I wired in a esp32 for blueretro in ps2 mode and that works

**Comment by nand2mario** [comment]
Xbox 360 controller is actually not supported. Currently only older (USB low-speed) controllers are working. Try something like this: https://www.aliexpress.us/item/3256802019916284.html

**Comment by s3anami** [comment]
I tried a different sd card and this is resolved. Seems to be picky on sd card choice
