### ISSUE TITLE
Color pattern screen only with v0.4 release and nestang-lite.fs

### ISSUE THREAD

**Issue by jon-nielsen** [nand2mario/nestang#4]
Hello,

Thought I'd report this as a follow up to the loader issue I've had. Now I've been able to test loader from Windows as well as the Linux version using a MangoPi MQ-Quad.

Software: Debian for the Mango Pi, loader 0.4, Contra, SMB1/2/3 .nes files.

My hardware setup is a Tang 20k lite with JTAG connection and PMOD HDMI. Controller is 8bitdo dongle which is recognized as an x360 controller.

Issue: Turning on power shows the color pattern. Loading a .nes file seemingly works. Loader transfers it. But the screen still shows color pattern only. Loader also detects input. I'm able to trigger OSD with LB (according to output log). The screen still stays with the pattern. Pressing LB a few times causes the screen to go black. I can load other games in the folder randomly by blindly pressing buttons, but no game seem to load correctly.

Please advise 

Thank you

**Comment by nand2mario** [comment]
Close because I cannot reproduce this.
