### ISSUE TITLE
[MMC5 mapper] Faulty emulation of MMC5

### ISSUE THREAD

**Issue by fjpolo** [nand2mario/nestang#48]
I was testing [Celeste Mario Hack](https://www.romhacking.net/hacks/7915/) and found out that apparently MMC5 mapper is not emulated correctly. 

![image](https://github.com/nand2mario/nestang/assets/9550134/c765a939-b436-4f8b-b17b-23a5044effdc)

**Comment by nand2mario** [comment]
Reproduced on my setup. MMC5 was not fully tested. I'll take a look.

**Comment by fjpolo** [comment]
Note: maybe [this NES_MISTer issue](https://github.com/MiSTer-devel/NES_MiSTer/pull/13/commits/36da4a03e99aa2207673b61a9d94a619d453a430) is the answer. To be checked.

**Comment by fjpolo** [comment]
Extra RAM bug fixed but still buggy

![IMG_20240323_174712](https://github.com/nand2mario/nestang/assets/9550134/cdcfc0e2-4cdc-4bb4-93a8-fcb0ec269d2f)
![IMG_20240323_174720](https://github.com/nand2mario/nestang/assets/9550134/f8a1a0cf-2764-400a-9d1d-1efccb586ac7)
![IMG_20240323_174742](https://github.com/nand2mario/nestang/assets/9550134/82189c95-5384-475c-80b2-ab4483098704)

**Comment by nand2mario** [comment]
This should be fixed in 0.9.
