### ISSUE TITLE
[0.9][Nano][Cannot load ROM][f_puts failed]  Latest master build won't load ROMs

### ISSUE THREAD

**Issue by fjpolo** [nand2mario/nestang#64]
I checked out latest `master` and built it myself. OSD seems to be working, if I place ROMS inside any `dir`  and press A on that dir, OSD goes back to main menu.

If I press options and try to change any options I get an error:

![IMG_20240409_154527](https://github.com/nand2mario/nestang/assets/9550134/dcea9e9a-ca16-4ff7-ae36-3fc0dd93ddcd)

If I try to load a ROM from root dir, there's an error:

![IMG_20240409_154707](https://github.com/nand2mario/nestang/assets/9550134/24ba6c3f-d746-4481-83b4-5e49dfdf2b4a)

FYI I tried using a  8Gb miniSD card formatted as FAT32 in 16kB sectors and also 2048bytes sectors, same result.

Anyone else having similar issues?

**Comment by fjpolo** [comment]
Aldo `Error opening director 99` comes up when choosing option `1)`

**Comment by mariogazziro** [comment]
Everything Works Fine to me and Also osd in nestang is better than snestang since It keeps transparency

**Comment by fjpolo** [comment]
Fixed in [v0.10 - NES/SNES controller suppor](https://github.com/nand2mario/nestang/releases/tag/v0.10)
