### ISSUE TITLE
8bitdo N30 2.4g gamepad not working

### ISSUE THREAD

**Issue by wolfshow** [nand2mario/nestang#68]
I followed the instruction from https://github.com/nand2mario/nestang/blob/master/doc/NESGamepad.md

but no response, I use nestang 0.9

**Comment by therealquaid** [comment]
I have the same problem. Also on 0.9.
Menu shows up and everything looks normal. But no response to the controller at all.

Is the menu supposed to be controllable with a NES controller?

**Comment by wolfshow** [comment]
Can @fjpolo help on this? Thanks!

**Comment by nand2mario** [comment]
I'm in the process of combining SNES and NES controller support. I'll update here when there's progress.

**Comment by wolfshow** [comment]
nestang 0.10 works very well.
