### ISSUE TITLE
Compile primer25k error

### ISSUE THREAD

**Issue by zzyyll2** [nand2mario/nestang#73]
![image](https://github.com/nand2mario/nestang/assets/22398806/27cd7d2f-7a8c-48ad-98d9-30ae210f97df)

Error occured when i compile it using primer25k type, it seems LUTs over limit then chip.

How to solve this problem?
Thanks.

**Comment by radiance28** [comment]
Don't change anything in Project - Configuration, use the default settings. The version of Gowin IDE should preferably be PRO (with free registered license), not EDU

**Comment by zzyyll2** [comment]
Got it, I will try it, thanks.

**Comment by zzyyll2** [comment]
Not work
1. use default settings.
2. use PRO IDE.


![image](https://github.com/nand2mario/nestang/assets/22398806/ce60df7c-30e3-45d9-92d5-d55f2160aaba)

**Comment by radiance28** [comment]
![image](https://github.com/nand2mario/nestang/assets/19339857/37a350a6-6a62-44da-b9f5-a88cc4120c42)


my version of IDE

**Comment by nand2mario** [comment]
@zzyyll2 Use 1.9.9 instead of 1.9.9.03 should solve your problem.
