### ISSUE TITLE
newbie question about nestang_nano20k.gprj

### ISSUE THREAD

**Issue by oldoldman** [nand2mario/nestang#90]
Hi guys,
When run synthsizing of the nestang_nano20k.gprj, I got the following error
```
ERROR (RP0006) : The number(27765(26541 LUTs, 882 ALUs, 0 ROM16s, 57 SSRAMs)) of logic in the design exceeds the resource limit(20736) of current device
```
How does this happen? Many thanks!

**Comment by fjpolo** [comment]
A couple followup questions :)

1. What branch are you on?
2. What version of GOWIN IDE are you using? EDU? Licensed?

**Comment by oldoldman** [comment]
I'm using nestang_nano20k.gprj on the master branch. And the IDE is EDU. BTW, I've tried nestang-0.7.2rc , which works fine.

**Comment by nand2mario** [comment]
Make sure you use Gowin 1.9.9. I use the Pro version (the Edu version should work). 1.9.10 does not work as Gowin somehow disabled SSRAM support in this release for some reason, which results in excessive resource usage.
