### ISSUE TITLE
What does "low-speed" refer to?

### ISSUE THREAD

**Issue by oldoldman** [nand2mario/nestang#94]
Hi guys,
I've wired my USB joystick up. But it does not work. 
1. I'm sure the wiring is correct because I can even charge my phone with the port
2. From https://github.com/nand2mario/nestang/blob/v0.6/doc/usb_gamepad.md , nestang only support "low-speed" joystick. So, I tested the joystick with ```libusb_get_device_speed``` which returned ```LIBUSB_SPEED_FULL(12MBit/s)```. This seems matching the speed of https://github.com/nand2mario/nestang/blob/v0.6/src/usb_gamepad.v#L5

So my question is the "low-speed" means ```LIBUSB_SPEED_LOW(1.5MBit/s)```?

**Comment by nand2mario** [comment]
Unfortunately, 12MBit/s is USB full-speed. The USB stack does need an update to support more devices.
